### ISSUE TITLE
How to upload video to youtube?

### ISSUE THREAD

**Issue by periyasamy25** [nodenica/youtube-node#11]
I want to upload videos to youtube using nodejs so please tell me how to upload videos to youtube using youtube-node.

**Comment by paulomcnally** [comment]
Today I will work in the method upload. I'll let you know by this means. Thanks

**Comment by paulomcnally** [comment]
@christopher-ramirez,  #youtube-query allow upload files?

**Comment by christopher-ramirez** [comment]
No. And I do think that this kind of feature is out of the scope of projects like *youtube-node* and *youtube-query*.

We should aim to limit our project scope to querying (reading) youtube public data in a simplified manner. Trying to do more than that is to fall in the "complete alternatives to Google's client" category. It would take a lot of work and it will be very difficult to out done Google.

This feature request should be closed.

**Comment by paulomcnally** [comment]
@periyasamy25 alternatives: https://www.npmjs.com/package/youtube-uploader https://www.npmjs.com/package/youtube-upload
