### ISSUE TITLE
getPlayListsById and getPlayListsItemsById badRequest (400) incompatibleParameters

### ISSUE THREAD

**Issue by edup** [nodenica/youtube-node#17]
getPlayListsById and getPlayListsItemsById is returning "badRequest (400) incompatibleParameters	The request specifies two or more parameters that cannot be used in the same request". This was experienced when you use the same instance to make search, getById and getPlayListsItemsById. After a some research I've verified that in the file app-youtube.js in the getPlayListsItemsById function, in spite you are clearing the Params, there are params like id and query that are still there, probably from the previous usage of the instance.

**Comment by paulomcnally** [comment]
Hi, all work ok.

Please share you're code with me to see and send you feedback

**Comment by edup** [comment]
Hi Paulo,

Apologise for the late reply.

I confirm that I need to create a new instance every time I want to use a function (search, related or even getPlaylist) otherwise it will use old arguments values in new calls.

My current code it’s something like this:

<code>
//It works because I create a new instance each time that I use methods of the class
var youtube = function() {
	var youTube = new YouTube();
	youTube.setKey(config["google-api-key"]);
	return youTube;
};

youtube().search(search_string, YOUTUBE_MAX_PER_PAGE, function(error, results);
youtube().related(youtube_id, YOUTUBE_MAX_PER_PAGE, cb;
</code>

<code>
//Doesn’t works because it seems that the self.getUrl(‘XXX’) method return an url that also have arguments from the previous calls
var youtube = new YouTube();
youtube.setKey(config["google-api-key"]);

youtube.search(search_string, YOUTUBE_MAX_PER_PAGE, cb);
youtube.related(youtube_id, YOUTUBE_MAX_PER_PAGE, cb);
</code>

For what I’ve seen in the lib/youtube.js you usually call the self.clearParts() but there’s not a self.clearParams() function.

I hope this helps to understand the problem.

Thanks for your support.

Eduardo
