### ISSUE TITLE
Not sure if this is an issue with the lib or api

### ISSUE THREAD

**Issue by TehPirat3** [nodenica/youtube-node#27]
When retrieving related videos, this is what happens
I'll use NCS Faded as the example

Pull related videos from Faded:
1st - NCS Spectre
2nd - NCS Faded

Pull related videos from Spectre:
1st - NCS Faded
2nd - NCS Spectre

This doesn't happen with every song, but at least half of what I've tried.

This looping is very annoying, if it's not an issue with the lib, can someone suggest a solution?

**Comment by paulomcnally** [comment]
This has nothing to do with the API
