### ISSUE TITLE
Old version of request causes warning on deprecated node-uuid package

### ISSUE THREAD

**Issue by robogeek** [nodenica/youtube-node#36]
I'm using youtube-node in one of my projects and get this message:

```
$ npm install 
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
... other output
```

The version of `request` listed in the dependencies explicitly references an older version of `request` that in turn relies on `node-uuid`.  Newer versions of `request` instead rely on `uuid` as the deprecation warning says to do.

It should be a simple matter to update the `package.json` for a new version of `request`.

**Comment by paulomcnally** [comment]
Please use v1.3.1. Thanks!!! https://www.npmjs.com/package/youtube-node
