### ISSUE TITLE
Potential fix for tests

### ISSUE THREAD

**Issue by TotomInc** [nodenica/youtube-node#48]
Tests are not passing due to YouTube API key not passed into travis-ci, since it is defined as a `process.env` variable.

@paulomcnally add a YouTube API key for travis-ci, you can read more about this [here](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings).

I tested this locally by running `YOUTUBE_API=my-key yarn run test` and it works fine.

**Comment by paulomcnally** [comment]
The previous key was blocked because it was not used.

I will proceed to change it.

Thanks for your notice.

**Comment by paulomcnally** [comment]
This has been solved. Thank you
